version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: "no"
    container_name: hintdog_mongo
    environment:
      - MONGO_INITDB_DATABASE=hintdog
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=local-root-password
    volumes:
      - ./mongodb/:/data/db/:rw
    networks:
      - main
    ports:
        - 127.0.0.1:27017:27017

networks:
  main:
    driver: bridge
